{% set name = "cis_interface" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - czmq
    - pip
    - python
    - sysv_ipc  # [unix]
    - zeromq
  run:
    - cerberus
    - czmq
    - jsonschema
    - matplotlib
    - nose
    - numpy
    - pandas
    - pint
    - psutil
    - pystache
    - python
    - pyyaml
    - pyzmq
    - scipy
    - sysv_ipc  # [unix]
    - unyt
    - zeromq
    - perf

test:
  imports:
    - cis_interface

about:
  home: https://github.com/cropsinsilico/yggdrasil/tree/cis_interface
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A framework for connecting computational models from multiple languages.'

  description: |
    The Crops in Silico (CiS) framework, cis_interface, provides support for
    connecting scientific models written in different programming languages.
    To connect two models, modelers add communications interfaces to the model code
    and provide declarative specification files that identfy the
    models that should be run and the inputs and outputs those models
    expect. cis_interface uses this information to launch the models
    on parallel processes and orchestrate asynchronous communication between them.
    Although designed for connecting crop models, cis_interface can be used to
    connect scientific models from any domain.
  doc_url: https://cropsinsilico.github.io/cis_interface
  dev_url: https://github.com/cropsinsilico/yggdrasil

extra:
  recipe-maintainers:
    - langmm
