# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

# branches to build
branches:
  # whitelist
  only:
    - topic/windows

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

os: Visual Studio 2015

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:

  global:
    PYTHON: "C:\\Miniconda3-x64"
    INSTALLZMQ: 1
    INSTALLRMQ: 1

  matrix:
    - platform: x64
      PYTHON_VERSION: "2.7"
      INSTALLRMQ: 0
    - platform: x64
      PYTHON_VERSION: "2.7"
    - platform: x64
      PYTHON_VERSION: "3.6"

install:
  - "SET MSVCVER=%APPVEYOR_BUILD_WORKER_IMAGE:~-2,2%"
  - "if %MSVCVER% gtr 11 set /a MSVCVER = MSVCVER - 1"
  - "SET VSINSTALLDIR=%ProgramFiles(x86)%\\Microsoft Visual Studio %MSVCVER%.0\\"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET MPLBACKEND=agg"

  # Setup Visual C++ toolset
  # TODO: Generic case. This is specific to 64bit VS 2015/2017 (14.0/16.0)
  - if "%MSVCVER%" == "16" if "%PLATFORM%" == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%MSVCVER%" == "14" if "%PLATFORM%" == "x64" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%MSVCVER%" == "14" if "%PLATFORM%" == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  # Create a conda environment
  - "conda update -q --yes conda"
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"

  # Check that we have the expected version of Python
  - "python --version"

  # Upgrade pip and setuptools and wheel to get clean install
  - "pip install --upgrade pip"
  - "pip install --upgrade wheel"
  - "pip install --upgrade setuptools"

  # Install ZeroMQ
  - "if %INSTALLZMQ% == 1 ci\\install-czmq-windows.bat"
  - "if %INSTALLZMQ% == 1 set PATH=%PATH%;C:\\projects\\build_czmq;C:\\projects\\build_libzmq\\lib\\Release"

  # Install & start RabbitMQ
  - "if %INSTALLRMQ% == 1 ci\\install-rmqserver-windows.bat"  
  - "if %INSTALLRMQ% == 1 ci\\start-rmqserver-windows.bat"  

  # Install dependencies using conda/pip
  - "conda install --yes -c conda-forge numpy nose coverage coveralls codecov flake8"
  - "conda install --yes -c conda-forge pystache pyyaml astropy scipy pika"
  - "pip install zmq"

  # Install cis_interface
  - "pip install -e ."

# Not a .NET project
build: false

before_test:
  # - "cl -lzmq -lczmq"
  - "flake8 cis_interface"

test_script:
  - "nosetests --nologcapture --with-coverage --cover-package=cis_interface -sv"

after_test:
  - "coveralls"
  - "codecov"
