# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

# branches to build
branches:
  # whitelist
  only:
    - topic/windows

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:

  global:
    PYTHON: "C:\\Miniconda3-x64"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.6"

platform:
  -x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET MPLBACKEND=agg"

  # Install the build and runtime dependencies of the project.
  # Create a conda environment
  - "conda update -q --yes conda"
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"

  # Check that we have the expected version of Python
  - "python --version"

  # Install specified version of numpy and dependencies
  - "conda install --yes -c conda-forge numpy nose coverage
  flake8 setuptools matplotlib scipy pyyaml pystache pika astropy"
  - "pip install sysv_ipc"
  - "pip install -e ."

# Not a .NET project
build: false

before_test:
  - "flake8 cis_interface"

test_script:
  - "nosetests --nologcapture --with-coverage --cover-package=cis_interface -sv cis_interface"

after_test:
  - "coveralls"