language: python
sudo: required
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    NUMPY=numpy
    MATPLOTLIB=matplotlib
    MPLBACKEND=agg
    INSTALLZMQ=1
    INSTALLRMQ=0
    INSTALLAPY=0
    INSTALLLPY=0

# services:
#   - rabbitmq

matrix:
  include:
    - python: 2.7
      env: NUMPY=numpy==1.13.0 MATPLOTLIB=matplotlib==1.5.3 INSTALLZMQ=0 INSTALLRMQ=0
    - python: 2.7
      env: INSTALLRMQ=1 INSTALLLPY=1
    - python: 3.4
    - python: 3.5
      env: INSTALLAPY=1
    - python: 3.6
      env: INSTALLZMQ=0 INSTALLRMQ=0
    - python: 3.6
      env: CIS_DEFAULT_COMM=ZMQComm INSTALLRMQ=1
    - os: osx
      env: INSTALLRMQ=0 INSTALLZMQ=0
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
         pip: false
         directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          # - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - os: osx
      env: INSTALLRMQ=0
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
         pip: false
         directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          # - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

before_install:
  - |
    sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    # Useful for debugging any issues with conda
    conda info -a

    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
       brew update
       # brew install ccache
       # export PATH=/usr/local/opt/ccache/libexec:$PATH
       brew install valgrind
    else
       pip install --upgrade virtualenv
       python -m virtualenv venv
       source venv/bin/activate
       export PATH=/usr/lib/ccache:$PATH
       sudo apt-get install strace valgrind
    fi

    # Install AstroPy
    if [[ $INSTALLAPY == '1' ]]; then
       echo Installing AstroPy...;
       pip install astropy
    fi

    # Install LPy
    if [[ $INSTALLLPY == '1' ]]; then
       echo Installing LPy...;
       sh ci/install-lpy-linux.sh
       # if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
       #    sh ci/install-lpy-osx.sh
       # else
       #    sh ci/install-lpy-linux.sh
       # fi
    fi

    # Install ZeroMQ
    if [[ $INSTALLZMQ == '1' ]]; then
       echo Installing ZeroMQ...;
       if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          sh ci/install-czmq-osx.sh
       else
          sh ci/install-czmq-linux.sh
       fi
    fi

    # Install RabbitMQ & Start a server
    if [[ $INSTALLRMQ == '1' ]]; then
       echo Installing RabbitMQ...;
       pip install pika
       if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          sh ci/install-rmqserver-osx.sh
       else
          sh ci/install-rmqserver-linux.sh
       fi

       echo Starting RabbitMQ...;
       if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          export PATH="${PATH}:/usr/local/sbin";
          sh ci/start-rmqserver-osx.sh
       else
          sh ci/start-rmqserver-linux.sh
       fi
       
    fi

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install $NUMPY
    pip install $MATPLOTLIB
    pip install nose coverage coveralls codecov flake8
    # Install cis_interface
    pip install -e .
    
before_script:
  - |
    flake8 cis_interface

script:
  - |
    nosetests --nologcapture --with-coverage --cover-package=cis_interface -svx

after_success:
  - coveralls
  - codecov
