comm:
  as_array: &id001
    required: false
    type: boolean
  field_names: &id002
    required: false
    schema:
      type: string
    type: list
  field_units: &id003
    required: false
    schema:
      type: string
    type: list
  format_str: &id004
    required: false
    type: string
  name: &id005
    required: true
    type: string
  onexit: &id006
    required: false
    type: string
  stype: &id007
    required: false
    type: integer
  type: &id008
    required: false
    type: string
  units: &id009
    required: false
    type: string
comm_schema_subtypes:
  CommBase:
  - default
  RMQComm:
  - rmq
comm_subtype_attr: _commtype
connection:
  input:
    excludes: input_file
    required: true
    schema:
      type: string
    type:
    - string
    - list
  input_file:
    excludes: input
    required: true
    schema:
      append: &id010
        required: false
        type: boolean
      as_array: *id001
      comment: &id011
        dependencies:
          filetype:
          - table
          - ascii
        required: false
        type: string
      delimiter: &id012
        dependencies:
          filetype:
          - table
          - pandas
        required: false
        type: string
      field_names: *id002
      field_units: *id003
      filetype: &id013
        allowed:
        - map
        - obj
        - binary
        - pickle
        - ply
        - table
        - ascii
        - pandas
        default: binary
        required: false
        type: string
      format_str: *id004
      in_temp: &id014
        required: false
        type: boolean
      is_series: &id015
        required: false
        type: boolean
      name: *id005
      newline: &id016
        default: '

          '
        required: false
        type: string
      onexit: *id006
      stype: *id007
      type: *id008
      units: *id009
      use_astropy: &id017
        dependencies:
          filetype:
          - table
        required: false
        type: boolean
      working_dir: &id018
        required: true
        type: string
    type: dict
  output:
    excludes: output_file
    required: true
    schema:
      type: string
    type:
    - string
    - list
  output_file:
    excludes: output
    required: true
    schema:
      append: *id010
      as_array: *id001
      comment: *id011
      delimiter: *id012
      field_names: *id002
      field_units: *id003
      filetype: *id013
      format_str: *id004
      in_temp: *id014
      is_series: *id015
      name: *id005
      newline: *id016
      onexit: *id006
      stype: *id007
      type: *id008
      units: *id009
      use_astropy: *id017
      working_dir: *id018
    type: dict
  translator:
    required: false
    schema:
      type: function
    type:
    - function
    - list
connection_schema_subtypes:
  AsciiFileInputDriver:
  - !!python/tuple
    - AsciiFileComm
    - DefaultComm
    - input
  AsciiFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiFileComm
    - output
  AsciiMapInputDriver:
  - !!python/tuple
    - AsciiMapComm
    - DefaultComm
    - input
  AsciiMapOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiMapComm
    - output
  AsciiTableInputDriver:
  - !!python/tuple
    - AsciiTableComm
    - DefaultComm
    - input
  AsciiTableOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiTableComm
    - output
  ConnectionDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - null
  FileInputDriver:
  - !!python/tuple
    - FileComm
    - DefaultComm
    - input
  FileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - FileComm
    - output
  InputDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - input
  ObjFileInputDriver:
  - !!python/tuple
    - ObjFileComm
    - DefaultComm
    - input
  ObjFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - ObjFileComm
    - output
  OutputDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - output
  PandasFileInputDriver:
  - !!python/tuple
    - PandasFileComm
    - DefaultComm
    - input
  PandasFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PandasFileComm
    - output
  PickleFileInputDriver:
  - !!python/tuple
    - PickleFileComm
    - DefaultComm
    - input
  PickleFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PickleFileComm
    - output
  PlyFileInputDriver:
  - !!python/tuple
    - PlyFileComm
    - DefaultComm
    - input
  PlyFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PlyFileComm
    - output
  RMQInputDriver:
  - !!python/tuple
    - RMQComm
    - DefaultComm
    - input
  RMQOutputDriver:
  - !!python/tuple
    - DefaultComm
    - RMQComm
    - output
file:
  append: *id010
  as_array: *id001
  comment: *id011
  delimiter: *id012
  field_names: *id002
  field_units: *id003
  filetype: *id013
  format_str: *id004
  in_temp: *id014
  is_series: *id015
  name: *id005
  newline: *id016
  onexit: *id006
  stype: *id007
  type: *id008
  units: *id009
  use_astropy: *id017
  working_dir: *id018
file_schema_subtypes:
  AsciiFileComm:
  - ascii
  AsciiMapComm:
  - map
  AsciiTableComm:
  - table
  FileComm:
  - binary
  ObjFileComm:
  - obj
  PandasFileComm:
  - pandas
  PickleFileComm:
  - pickle
  PlyFileComm:
  - ply
file_subtype_attr: _filetype
model:
  args:
    required: true
    schema:
      type: string
    type:
    - list
    - string
  builddir:
    dependencies:
      language:
      - cmake
    required: false
    type: string
  cc:
    dependencies:
      language:
      - c
      - c++
      - cpp
    required: false
    type: string
  client_of:
    required: false
    schema:
      type: string
    type: list
  cmakeargs:
    dependencies:
      language:
      - cmake
    required: false
    schema:
      type: string
    type: list
  inputs:
    required: false
    schema:
      schema:
        as_array: *id001
        field_names: *id002
        field_units: *id003
        format_str: *id004
        name: *id005
        onexit: *id006
        stype: *id007
        type: *id008
        units: *id009
      type: dict
    type: list
  is_server:
    required: false
    type: boolean
  language:
    allowed:
    - c
    - cmake
    - lpy
    - python
    - make
    - executable
    - c++
    - matlab
    - cpp
    required: true
    type: string
  make_command:
    dependencies:
      language:
      - make
    required: false
    type: string
  makedir:
    dependencies:
      language:
      - make
    required: false
    type: string
  makefile:
    dependencies:
      language:
      - make
    required: false
    type: string
  name:
    required: true
    type: string
  outputs:
    required: false
    schema:
      schema:
        as_array: *id001
        field_names: *id002
        field_units: *id003
        format_str: *id004
        name: *id005
        onexit: *id006
        stype: *id007
        type: *id008
        units: *id009
      type: dict
    type: list
  sourcedir:
    dependencies:
      language:
      - cmake
    required: false
    type: string
  strace_flags:
    required: false
    schema:
      type: string
    type: list
  valgrind_flags:
    required: false
    schema:
      type: string
    type: list
  with_strace:
    required: false
    type: boolean
  with_valgrind:
    required: false
    type: boolean
  working_dir:
    required: true
    type: string
model_schema_subtypes:
  CMakeModelDriver:
  - cmake
  GCCModelDriver:
  - c
  - c++
  - cpp
  LPyModelDriver:
  - lpy
  MakeModelDriver:
  - make
  MatlabModelDriver:
  - matlab
  ModelDriver:
  - executable
  PythonModelDriver:
  - python
model_subtype_attr: _language
