additionalProperties: false
definitions:
  comm:
    $id: '#comm'
    allOf:
    - additionalProperties: false
      dependencies:
        driver:
        - args
      properties:
        args:
          type: string
        as_array:
          default: false
          type: boolean
        commtype:
          default: default
          enum:
          - ipc
          - default
          - zmq
          - rmq
          type: string
        datatype:
          default:
            type: bytes
          type: schema
        driver:
          type: string
        field_names:
          items:
            type: string
          type: array
        field_units:
          items:
            type: string
          type: array
        name:
          type: string
        recv_converter:
          type: function
        send_converter:
          type: function
      required:
      - name
      - commtype
      - datatype
      type: object
    - anyOf:
      - properties:
          commtype:
            enum:
            - default
        title: DefaultComm
      - properties:
          commtype:
            enum:
            - rmq
        title: RMQComm
      - properties:
          commtype:
            enum:
            - ipc
        title: IPCComm
      - properties:
          commtype:
            enum:
            - zmq
        title: ZMQComm
    description: Schema for comm components.
    title: comm
  connection:
    $id: '#connection'
    allOf:
    - additionalProperties: false
      dependencies:
        driver:
        - args
      properties:
        args:
          type: string
        direction:
          enum:
          - input
          - output
          - null
        driver:
          type: string
        icomm_type:
          enum:
          - AsciiFileComm
          - DefaultComm
          - ObjFileComm
          - AsciiTableComm
          - PickleFileComm
          - AsciiMapComm
          - FileComm
          - RMQComm
          - PandasFileComm
          - PlyFileComm
        inputs:
          items:
            anyOf:
            - $ref: '#/definitions/comm'
            - $ref: '#/definitions/file'
          minItems: 1
          type: array
        ocomm_type:
          enum:
          - AsciiFileComm
          - DefaultComm
          - PickleFileComm
          - AsciiTableComm
          - ObjFileComm
          - AsciiMapComm
          - FileComm
          - RMQComm
          - PandasFileComm
          - PlyFileComm
        onexit:
          type: string
        outputs:
          items:
            anyOf:
            - $ref: '#/definitions/comm'
            - $ref: '#/definitions/file'
          minItems: 1
          type: array
        translator:
          items:
            type: function
          type: array
      required:
      - inputs
      - outputs
      type: object
    - anyOf:
      - properties:
          direction:
            enum:
            - null
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - DefaultComm
        title: ConnectionDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - FileComm
        title: FileOutputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - PandasFileComm
        title: PandasFileOutputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - AsciiMapComm
        title: AsciiMapOutputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - FileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: FileInputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - ObjFileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: ObjFileInputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - PickleFileComm
        title: PickleFileOutputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - AsciiMapComm
          ocomm_type:
            enum:
            - DefaultComm
        title: AsciiMapInputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - AsciiFileComm
        title: AsciiFileOutputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - AsciiTableComm
        title: AsciiTableOutputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - AsciiFileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: AsciiFileInputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - AsciiTableComm
          ocomm_type:
            enum:
            - DefaultComm
        title: AsciiTableInputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - DefaultComm
        title: OutputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - RMQComm
        title: RMQOutputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - PlyFileComm
        title: PlyFileOutputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - DefaultComm
        title: InputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - RMQComm
          ocomm_type:
            enum:
            - DefaultComm
        title: RMQInputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - PlyFileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: PlyFileInputDriver
      - properties:
          direction:
            enum:
            - output
          icomm_type:
            enum:
            - DefaultComm
          ocomm_type:
            enum:
            - ObjFileComm
        title: ObjFileOutputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - PickleFileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: PickleFileInputDriver
      - properties:
          direction:
            enum:
            - input
          icomm_type:
            enum:
            - PandasFileComm
          ocomm_type:
            enum:
            - DefaultComm
        title: PandasFileInputDriver
    description: Schema for connection components.
    title: connection
  file:
    $id: '#file'
    allOf:
    - additionalProperties: false
      dependencies:
        driver:
        - args
      properties:
        append:
          default: false
          type: boolean
        args:
          type: string
        as_array:
          default: false
          type: boolean
        comment:
          default: '# '
          type: unicode
        delimiter: &id001
          default: "\t"
          type: unicode
        driver:
          type: string
        field_names:
          items:
            type: string
          type: array
        field_units:
          items:
            type: string
          type: array
        filetype:
          default: binary
          enum:
          - binary
          - pandas
          - mat
          - pickle
          - table
          - map
          - ascii
          - obj
          - ply
          type: string
        format_str: &id002
          type: string
        in_temp:
          default: false
          type: boolean
        is_series:
          default: false
          type: boolean
        name:
          type: string
        newline:
          default: '

            '
          type: unicode
        recv_converter:
          type: function
        send_converter:
          type: function
        use_astropy: &id003
          default: false
          type: boolean
        working_dir:
          type: string
      required:
      - name
      - filetype
      - working_dir
      type: object
    - anyOf:
      - properties:
          filetype:
            enum:
            - binary
        title: FileComm
      - properties:
          delimiter: *id001
          filetype:
            enum:
            - map
        title: AsciiMapComm
      - properties:
          filetype:
            enum:
            - ply
        title: PlyFileComm
      - properties:
          filetype:
            enum:
            - ascii
        title: AsciiFileComm
      - properties:
          delimiter:
            default: "\t"
            type: unicode
          filetype:
            enum:
            - table
          format_str: *id002
          use_astropy: *id003
        title: AsciiTableComm
      - properties:
          filetype:
            enum:
            - mat
        title: MatFileComm
      - properties:
          delimiter:
            default: "\t"
            type: unicode
          filetype:
            enum:
            - pandas
          format_str:
            type: string
          use_astropy:
            default: false
            type: boolean
        title: PandasFileComm
      - properties:
          filetype:
            enum:
            - obj
        title: ObjFileComm
      - properties:
          filetype:
            enum:
            - pickle
        title: PickleFileComm
    description: Schema for file components.
    title: file
  model:
    $id: '#model'
    allOf:
    - additionalProperties: false
      dependencies:
        driver:
        - args
      properties:
        args:
          items:
            type: string
          type: array
        builddir: &id008
          type: string
        cc: &id004
          type: string
        client_of:
          default: []
          items:
            type: string
          type: array
        cmakeargs: &id009
          default: []
          items:
            type: string
          type: array
        driver:
          type: string
        inputs:
          default: []
          items:
            $ref: '#/definitions/comm'
          type: array
        is_server:
          default: false
          type: boolean
        language:
          enum:
          - c++
          - matlab
          - python
          - c
          - cmake
          - lpy
          - make
          - executable
          - cpp
          type: string
        make_command: &id005
          default: make
          type: string
        makedir: &id006
          type: string
        makefile: &id007
          default: Makefile
          type: string
        name:
          type: string
        outputs:
          default: []
          items:
            $ref: '#/definitions/comm'
          type: array
        sourcedir: &id010
          type: string
        strace_flags:
          default: []
          items:
            type: string
          type: array
        valgrind_flags:
          default:
          - --leak-check=full
          items:
            type: string
          type: array
        with_strace:
          default: false
          type: boolean
        with_valgrind:
          default: false
          type: boolean
        working_dir:
          type: string
      required:
      - name
      - language
      - args
      - working_dir
      type: object
    - anyOf:
      - properties:
          language:
            enum:
            - executable
        title: ModelDriver
      - properties:
          cc: *id004
          language:
            enum:
            - c
            - c++
            - cpp
        title: GCCModelDriver
      - properties:
          language:
            enum:
            - make
          make_command: *id005
          makedir: *id006
          makefile: *id007
        title: MakeModelDriver
      - properties:
          language:
            enum:
            - lpy
        title: LPyModelDriver
      - properties:
          language:
            enum:
            - matlab
        title: MatlabModelDriver
      - properties:
          builddir: *id008
          cmakeargs: *id009
          language:
            enum:
            - cmake
          sourcedir: *id010
        title: CMakeModelDriver
      - properties:
          language:
            enum:
            - python
        title: PythonModelDriver
    description: Schema for model components.
    title: model
description: Schema for cis_interface YAML input files.
properties:
  connections:
    items:
      $ref: '#/definitions/connection'
    type: array
  models:
    items:
      $ref: '#/definitions/model'
    minItems: 1
    type: array
required:
- models
title: YAML Schema
type: object
