comm:
  as_array: &id003
    coerce: &id002 !str_to_bool {}
    required: false
    type: boolean
  field_names: &id004
    coerce: &id001 !str_to_list {}
    required: false
    schema:
      type: string
    type: list
  field_units: &id005
    coerce: *id001
    required: false
    schema:
      type: string
    type: list
  format_str: &id006
    required: false
    type: string
  name: &id007
    required: true
    type: string
  onexit: &id008
    required: false
    type: string
  stype: &id009
    coerce: !str_to_int {}
    required: false
    type: integer
  type: &id010
    required: false
    type: string
  units: &id011
    required: false
    type: string
comm_schema_subtypes:
  CommBase:
  - default
  RMQComm:
  - rmq
comm_subtype_attr: _commtype
connection:
  input:
    excludes: input_file
    required: true
    type: string
  input_file:
    excludes: input
    required: true
    schema:
      append: &id012
        coerce: *id002
        default: false
        required: false
        type: boolean
      as_array: *id003
      comment: &id013
        dependencies:
          filetype:
          - table
          - ascii
        required: false
        type: string
      delimiter: &id014
        dependencies:
          filetype:
          - table
          - pandas
        required: false
        type: string
      field_names: *id004
      field_units: *id005
      filetype: &id015
        allowed:
        - map
        - obj
        - binary
        - pickle
        - ply
        - table
        - ascii
        - pandas
        default: binary
        required: false
        type: string
      format_str: *id006
      in_temp: &id016
        coerce: *id002
        default: false
        required: false
        type: boolean
      is_series: &id017
        coerce: *id002
        default: false
        required: false
        type: boolean
      name: *id007
      newline: &id018
        default: '

          '
        required: false
        type: string
      onexit: *id008
      stype: *id009
      type: *id010
      units: *id011
      use_astropy: &id019
        coerce: *id002
        dependencies:
          filetype:
          - table
        required: false
        type: boolean
      working_dir: &id020
        required: true
        type: string
    type: dict
  output:
    excludes: output_file
    required: true
    type: string
  output_file:
    excludes: output
    required: true
    schema:
      append: *id012
      as_array: *id003
      comment: *id013
      delimiter: *id014
      field_names: *id004
      field_units: *id005
      filetype: *id015
      format_str: *id006
      in_temp: *id016
      is_series: *id017
      name: *id007
      newline: *id018
      onexit: *id008
      stype: *id009
      type: *id010
      units: *id011
      use_astropy: *id019
      working_dir: *id020
    type: dict
  translator:
    coerce: !str_to_function {}
    required: false
    validator: !validate_function {}
connection_schema_subtypes:
  AsciiFileInputDriver:
  - !!python/tuple
    - AsciiFileComm
    - DefaultComm
    - input
  AsciiFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiFileComm
    - output
  AsciiMapInputDriver:
  - !!python/tuple
    - AsciiMapComm
    - DefaultComm
    - input
  AsciiMapOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiMapComm
    - output
  AsciiTableInputDriver:
  - !!python/tuple
    - AsciiTableComm
    - DefaultComm
    - input
  AsciiTableOutputDriver:
  - !!python/tuple
    - DefaultComm
    - AsciiTableComm
    - output
  ConnectionDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - null
  FileInputDriver:
  - !!python/tuple
    - FileComm
    - DefaultComm
    - input
  FileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - FileComm
    - output
  InputDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - input
  ObjFileInputDriver:
  - !!python/tuple
    - ObjFileComm
    - DefaultComm
    - input
  ObjFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - ObjFileComm
    - output
  OutputDriver:
  - !!python/tuple
    - DefaultComm
    - DefaultComm
    - output
  PandasFileInputDriver:
  - !!python/tuple
    - PandasFileComm
    - DefaultComm
    - input
  PandasFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PandasFileComm
    - output
  PickleFileInputDriver:
  - !!python/tuple
    - PickleFileComm
    - DefaultComm
    - input
  PickleFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PickleFileComm
    - output
  PlyFileInputDriver:
  - !!python/tuple
    - PlyFileComm
    - DefaultComm
    - input
  PlyFileOutputDriver:
  - !!python/tuple
    - DefaultComm
    - PlyFileComm
    - output
  RMQInputDriver:
  - !!python/tuple
    - RMQComm
    - DefaultComm
    - input
  RMQOutputDriver:
  - !!python/tuple
    - DefaultComm
    - RMQComm
    - output
file:
  append: *id012
  as_array: *id003
  comment: *id013
  delimiter: *id014
  field_names: *id004
  field_units: *id005
  filetype: *id015
  format_str: *id006
  in_temp: *id016
  is_series: *id017
  name: *id007
  newline: *id018
  onexit: *id008
  stype: *id009
  type: *id010
  units: *id011
  use_astropy: *id019
  working_dir: *id020
file_schema_subtypes:
  AsciiFileComm:
  - ascii
  AsciiMapComm:
  - map
  AsciiTableComm:
  - table
  FileComm:
  - binary
  ObjFileComm:
  - obj
  PandasFileComm:
  - pandas
  PickleFileComm:
  - pickle
  PlyFileComm:
  - ply
file_subtype_attr: _filetype
model:
  args:
    required: true
    schema:
      coerce: !any_to_str {}
      type: string
    type:
    - list
    - string
  builddir:
    dependencies:
      language:
      - cmake
    required: false
    type: string
  cc:
    dependencies:
      language:
      - c
      - c++
      - cpp
    required: false
    type: string
  client_of:
    required: false
    schema:
      type: string
    type: list
  cmakeargs:
    dependencies:
      language:
      - cmake
    required: false
    schema:
      type: string
    type: list
  inputs:
    required: false
    schema:
      schema:
        as_array: *id003
        field_names: *id004
        field_units: *id005
        format_str: *id006
        name: *id007
        onexit: *id008
        stype: *id009
        type: *id010
        units: *id011
      type: dict
    type: list
  is_server:
    coerce: *id002
    required: false
    type: boolean
  language:
    allowed:
    - c
    - cmake
    - lpy
    - python
    - make
    - executable
    - c++
    - matlab
    - cpp
    required: true
    type: string
  make_command:
    dependencies:
      language:
      - make
    required: false
    type: string
  makedir:
    dependencies:
      language:
      - make
    required: false
    type: string
  makefile:
    dependencies:
      language:
      - make
    required: false
    type: string
  name:
    required: true
    type: string
  outputs:
    required: false
    schema:
      schema:
        as_array: *id003
        field_names: *id004
        field_units: *id005
        format_str: *id006
        name: *id007
        onexit: *id008
        stype: *id009
        type: *id010
        units: *id011
      type: dict
    type: list
  sourcedir:
    dependencies:
      language:
      - cmake
    required: false
    type: string
  strace_flags:
    coerce: *id002
    required: false
    schema:
      type: string
    type: list
  valgrind_flags:
    coerce: *id002
    required: false
    schema:
      type: string
    type: list
  with_strace:
    coerce: *id002
    required: false
    type: boolean
  with_valgrind:
    coerce: *id002
    required: false
    type: boolean
  working_dir:
    required: true
    type: string
model_schema_subtypes:
  CMakeModelDriver:
  - cmake
  GCCModelDriver:
  - c
  - c++
  - cpp
  LPyModelDriver:
  - lpy
  MakeModelDriver:
  - make
  MatlabModelDriver:
  - matlab
  ModelDriver:
  - executable
  PythonModelDriver:
  - python
model_subtype_attr: _language
